package com.watsoo.device.management.enums;

public enum StatusMaster {

	TESTED, DEVICE_PACKED, READY, BOX_PACKED, BOX_IN_STOCK, BOX_DISPATCH_FULLY, BOX_DISPATCH_PARTIALLY, ISSUED_DEVICES,
	REPLACED_DEVICE
}
